/*
rem otorgar privilegio de lectura de la tabla hr.employees
rem al usuario sergiohr 
rem tabla que es propietario el usuario HR
rem otorgarlo desde el usuario SYS
*/)

grant select on hr.employees to sergiohr;
grant select on hr.departments to sergiohr;

REM VARIAS QUERYS DE ESQUEMA HR
REM
SELECT EMPLOYEE_ID, LAST_NAME,EMAIL FROM HR.EMPLOYEES
WHERE ROWNUM <= 15;

SELECT EMPLOYEE_ID, LAST_NAME,EMAIL,HIRE_DATE,MANAGER_ID,DEPARTMENT_ID FROM HR.EMPLOYEES
WHERE ROWNUM <= 15;

SELECT EMPLOYEE_ID, LAST_NAME,EMAIL,HIRE_DATE,MANAGER_ID,DEPARTMENT_ID FROM HR.EMPLOYEES
WHERE ROWNUM <= 15 OR EMPLOYEE_ID = 178;

SELECT EMPLOYEE_ID, LAST_NAME,EMAIL,DEPARTMENT_ID FROM HR.EMPLOYEES
WHERE EMPLOYEE_ID > 200;

SELECT EMPLOYEE_ID, LAST_NAME,EMAIL,DEPARTMENT_ID FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID IS NULL;

SELECT COUNT(*) FROM HR.EMPLOYEES;

SELECT NVL(DEPARTMENT_ID,999999) DEPTO, EMPLOYEE_ID  FROM HR.EMPLOYEES
	WHERE DEPARTMENT_ID IS NULL;

SELECT DISTINCT DEPARTMENT_ID FROM HR.EMPLOYEES
	ORDER BY 1;


REM CREAR TABLE DEL EJEMPLO INTEGRIDAD REFENCIAL DEL MANUAL DE ORACLE
REM CREA TABLA EMPLOYEES3
DROP TABLE EMPLOYEES3;
REM 
CREATE TABLE EMPLOYEES3 AS 
SELECT EMPLOYEE_ID, LAST_NAME,EMAIL,HIRE_DATE,MANAGER_ID,DEPARTMENT_ID
	FROM HR.EMPLOYEES
	WHERE ROWNUM <= 15 OR EMPLOYEE_ID = 178;

COL EMPLOYEE_ID FORMAT 99999
COL LAST_NAME   FORMAT A10
COL EMAIL       FORMAT A10
COL HIRE_DATE   FORMAT A10
COL MANAGER_ID  FORMAT 99999
COL DEPARTMENT_ID FORMAT 999
SELECT * FROM EMPLOYEES3 ORDER BY 1;

REM CREA TABLA DEPARTMENTS3
REM 
DROP TABLE DEPARTMENTS3;
REM 



CREATE TABLE DEPARTMENTS3 AS
SELECT DEPARTMENT_ID, DEPARTMENT_NAME,MANAGER_ID
	FROM HR.DEPARTMENTS
	WHERE DEPARTMENT_ID <=110;

REM 
COL DEPARTMENT_ID FORMAT 9999
COL DEPARTMENT_NAME FORMAT A24
COL  MANAGER_ID FORMAT 99999
SELECT * FROM DEPARTMENTS3;
REM 

ALTER TABLE EMPLOYEES3
	ADD CONSTRAINT EMPLOYEES3_PK 
		PRIMARY KEY (EMPLOYEE_ID);

ALTER TABLE DEPARTMENTS3	
		ADD CONSTRAINT DEPARTMENTS3_PK
		PRIMARY KEY (DEPARTMENT_ID);



ALTER TABLE EMPLOYEES3		
		ADD CONSTRAINT EMPLO3_DEPART3_FK 
		FOREIGN KEY (DEPARTMENT_ID)
		REFERENCES DEPARTMENTS3(DEPARTMENT_ID)
		deferrable;
/*		
seccion de consultas a la base de datos
actualizacion y borrado
	
*/	
select employee_id,last_name,d3.manager_id
	, d3.department_id,department_name
	from departments3 d3,employees3 e3
	where d3.department_id = e3.department_id;

insert into employees3 
	values(207,'Ashdown','AASHDOWN',to_date('17-DEC-07'),100,99);
REM EL EMPLEADO 207 VIOLA LA INTEGRIDAD REFERENCIAL
insert into employees3 
	values(208,'Green','BGREEN',to_date('17-DEC-07'),101,null);
REM EL EMPLEADO 208 SE PERMITE PORQUE EL DEPARTAMENTO ES NULL 
insert into employees3 
	values(207,'Ashdown','AASHDOWN',to_date('17-DEC-07'),100,99);
REM EL EMPLEADO 209 SE PERMITE AL INGRESAR AL DEPARTAMENTO   30
insert into employees3 
	values(209,'Ramirez','RRAMIREZ',to_date('17-DEC-07'),100,30);

REM
SELECT * FROM DEPARTMENTS3;
SELECT * FROM EMPLOYEES3;

/*
seccion de actualizacion y borrado
*/
COLUMN OWNER FORMAT A17
COLUMN NOMBRE FORMAT A18
COLUMN TABLE_NAME FORMAT A12
select owner
	, constraint_name NOMBRE
	, constraint_type TIPO
	, table_name 
	, status
	, deferrable
	, deferred
	,INDEX_NAME
	from user_constraints
	where owner = 'SERGIOHR'
	ORDER BY 4,2;
	
COL COLUMN_NAME FORMAT A23	
SELECT OWNER
	, CONSTRAINT_NAME
	, TABLE_NAME
	, COLUMN_NAME
	FROM USER_CONS_COLUMNS
	ORDER BY 3,4;

select employee_id,last_name,d3.manager_id
	, d3.department_id,department_name
	from departments3 d3,employees3 e3
	where d3.department_id = e3.department_id;		

REM
REM
DROP TABLE DEPARTMENTS3    CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEES3       CASCADE CONSTRAINTS;
