spool C:\Users\ORA_bases\Pag_511.txt
REM  FIGURA 10.5 & 10.6 LIBRO NAVATHE 
rem pags. 345 & 346 de la 5th edition.
REM  FIGURA 15.5 & 15.6 LIBRO NAVATHE 
rem pags.   511 & 512 de la 6th edition

DESC DEPT_LOCATIONS
DESC WORKS_ON
DROP TABLE EMP_LOCS;
CREATE TABLE EMP_LOCS AS
SELECT LNAME,DLOCATION
	FROM EMPLOYEE,DEPT_LOCATIONS
	WHERE DNUMBER =DNO;

DROP TABLE EMP_PROJ1;
CREATE TABLE EMP_PROJ1 AS	
SELECT ESSN,PNUMBER,HOURS,PNAME,PLOCATION
	FROM WORKS_ON,PROJECT
	WHERE PNO=PNUMBER;
	
SELECT * FROM EMP_LOCS;
SELECT * FROM EMP_PROJ1;

SELECT * FROM EMP_LOCS NATURAL JOIN EMP_PROJ1;
spool off


