/*
EJEMPLO NO 3  CONTINUACIÓN 
  DIAPOSITIVAS DE NAVATHE PAG 6 2A PARTE 
  NONADDITIVE LOSSLESS-JOIN_DECOMPOSITION
SCHEMA  < R=ABC, F= { A->B }  > 
   AND PARTITION D2 = { AB, AC}
*/

DROP TABLE REX_3;
create table REX_3(
	A NUMBER(2),
	B NUMBER(2),
	C NUMBER(2));
INSERT INTO REX_3 VALUES (1,2,3);
INSERT INTO REX_3 VALUES (1,2,4);
INSERT INTO REX_3 VALUES (2,1,1);
INSERT INTO REX_3 VALUES (3,1,0);
INSERT INTO REX_3 VALUES (3,1,4);

SELECT A,B FROM REX_3 ORDER BY 1,2;

SELECT A,C FROM REX_3 ORDER BY 1,2;

drop table REX_3_R1;
create table REX_3_R1 AS
SELECT distinct A,B FROM REX_3 ORDER BY 1;
select a,b from REX_3_R1;

drop table REX_3_R3;
create table REX_3_R3 AS
SELECT distinct A,C FROM REX_3 ORDER BY 1;
select A,C from REX_3_R3;


DROP TABLE REX_3_JOIN_N_2;
CREATE TABLE REX_3_JOIN_N_2 AS
SELECT A,B,C FROM REX_3_R1 NATURAL JOIN REX_3_R3 ORDER BY 1,2,3; 
SELECT * FROM REX_3_JOIN_N ORDER BY 1,2,3;

REM PRIMER OPERANDO RELACION *JOIN NATURAL
REM PARA DETERMINAR LAS TUPLAS ESPURIAS
REM SI NO DESPLIEGA NINGUNA 
REM  IMPLICA QUE ES UNA REUNION SIN PERDIDA 
REM Y QUE NO IMPLICA TUPLAS ESPUREAS.
REM  
select a,b,c from REX_3_JOIN_N_2
	where (a,b,c) not in
	(
		select a,b,c from REX_3
	)
	order by 1,2,3;
REM PARA DESPLEGAR LAS TUPLAS ORIGINALES  
select a,b,c from REX_3_JOIN_N_2
	where (a,b,c)  in
	(
		select a,b,c from REX_3
	)
	order by 1,2,3;


